"""Settings view — API key configuration with validation and persistence."""

from __future__ import annotations

import logging
import os
import sys

import flet as ft

from lupe.flet.theme import CYAN, MATRIX_GREEN, TEXT_SECONDARY

logger = logging.getLogger(__name__)

# Provider signup URLs for help text
SIGNUP_URLS: dict[str, str] = {
    "openai": "https://platform.openai.com/signup",
    "anthropic": "https://console.anthropic.com/signup",
    "openrouter": "https://openrouter.ai/signup",
    "virustotal": "https://www.virustotal.com/gui/join-us",
    "abuseipdb": "https://www.abuseipdb.com/register",
    "shodan": "https://account.shodan.io/register",
    "otx": "https://otx.alienvault.com/signup",
    "urlscan": "https://urlscan.io/user/signup/",
    "hibp": "https://haveibeenpwned.com/API/Key",
    "greynoise": "https://www.greynoise.io/signup",
    "ipqs": "https://www.ipqualityscore.com/create-account",
    "numverify": "https://numverify.com/signup",
    "misp": "https://www.misp-project.org/",
    "censys": "https://censys.io/register",
    "hybrid_analysis": "https://www.hybrid-analysis.com/signup",
    "gemini": "https://aistudio.google.com/app/apikey",
}

# Field definitions: (key, label, is_password)
FIELDS: list[tuple[str, str, bool]] = [
    ("llm_provider", "LLM Provider (ollama / openai / anthropic / openrouter / gemini)", False),
    ("ollama_url", "Ollama URL", False),
    ("openai_key", "OpenAI API Key", True),
    ("anthropic_key", "Anthropic API Key", True),
    ("openrouter_key", "OpenRouter API Key", True),
    ("gemini_key", "Gemini API Key", True),
    ("virustotal_key", "VirusTotal Key", True),
    ("abuseipdb_key", "AbuseIPDB Key", True),
    ("shodan_key", "Shodan Key", True),
    ("otx_key", "OTX Key", True),
    ("urlscan_key", "URLScan Key", True),
    ("hibp_key", "HaveIBeenPwned Key", True),
    ("greynoise_key", "GreyNoise Key", True),
    ("ipqs_key", "IPQS Key", True),
    ("numverify_key", "NumVerify Key", True),
    ("misp_url", "MISP URL", False),
    ("misp_key", "MISP API Key", True),
    ("censys_id", "Censys ID", False),
    ("censys_secret", "Censys Secret", True),
    ("hybrid_analysis_key", "Hybrid Analysis Key", True),
]


def _get_config_path() -> str:
    """Return the path to the Lupe TOML config file."""
    from lupe.config import get_config_dir

    return str(get_config_dir() / "lupe.toml")


def validate_key_format(provider: str, value: str) -> bool:
    """Validate an API key format for the given provider.

    Returns True if the key appears valid, False otherwise.
    """
    if not value or not value.strip():
        return False

    value = value.strip()

    # URL validation for url fields
    if provider in ("ollama_url", "misp_url"):
        return value.startswith("http://") or value.startswith("https://")

    # Provider-specific prefix validation
    prefix_rules: dict[str, str] = {
        "openai": "sk-",
        "anthropic": "sk-ant-",
        "openrouter": "sk-or-",
    }

    if provider in prefix_rules:
        return value.startswith(prefix_rules[provider]) and len(value) > 10

    # Generic: non-empty is sufficient
    return len(value) > 0


def save_settings(settings: dict[str, str]) -> None:
    """Save settings dict to TOML config file with restrictive permissions.

    Creates parent directories if needed.
    On Unix, sets file permissions to 600 (owner read/write only).
    """
    config_path_str = _get_config_path()
    from pathlib import Path

    config_path = Path(config_path_str)
    config_path.parent.mkdir(parents=True, exist_ok=True)

    # Filter out empty values
    clean = {k: v for k, v in settings.items() if v}

    # Write TOML
    lines = ["# Lupe CTI configuration", "# Generated by lupe-desktop", ""]
    for key, value in sorted(clean.items()):
        escaped = value.replace('"', '\\"')
        lines.append(f'{key} = "{escaped}"')

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Set restrictive permissions on Unix
    if sys.platform != "win32":
        try:
            os.chmod(config_path, 0o600)
        except OSError:
            logger.warning("Could not set permissions on %s", config_path)


def load_settings() -> dict[str, str]:
    """Load settings from the TOML config file.

    Returns an empty dict if the file doesn't exist.
    """
    config_path_str = _get_config_path()
    from pathlib import Path

    config_path = Path(config_path_str)
    if not config_path.exists():
        return {}

    try:
        from lupe.compat import tomllib

        with open(config_path, "rb") as f:
            data = tomllib.load(f)
        return {k: str(v) for k, v in data.items() if isinstance(v, str | int | float | bool)}
    except Exception:
        logger.warning("Failed to load config from %s", config_path, exc_info=True)
        return {}


def build_settings_view(page: ft.Page) -> ft.Control:
    """Build the settings view with API key inputs.

    Args:
        page: The Flet page (for launch_url).

    Returns:
        A Flet Column control for the settings view.
    """
    # Load existing settings
    existing = load_settings()

    # Track input controls by key
    inputs: dict[str, ft.TextField] = {}

    def on_signup_click(e: ft.ControlEvent, provider: str) -> None:
        """Open signup URL in browser."""
        url = SIGNUP_URLS.get(provider, "")
        if url:
            page.launch_url(url)

    def on_save_click(e: ft.ControlEvent) -> None:
        """Save all settings."""
        settings: dict[str, str] = {}
        for key, _, _ in FIELDS:
            tf = inputs.get(key)
            if tf and tf.value and tf.value.strip():
                settings[key] = tf.value.strip()
        save_settings(settings)
        status_text.value = "Settings saved successfully!"
        status_text.color = MATRIX_GREEN
        page.update()

    def on_test_click(e: ft.ControlEvent) -> None:
        """Validate key formats."""
        invalid = []
        for key, label, _ in FIELDS:
            tf = inputs.get(key)
            if tf and tf.value and tf.value.strip():
                if not validate_key_format(key, tf.value):
                    invalid.append(label)
        if invalid:
            status_text.value = f"Invalid format: {', '.join(invalid)}"
            status_text.color = "#ff5555"
        else:
            status_text.value = "All keys appear valid."
            status_text.color = MATRIX_GREEN
        page.update()

    status_text = ft.Text("", size=14)

    # Build field groups
    llm_fields: list[ft.Control] = [
        ft.Text("LLM Provider", size=16, color=CYAN, weight=ft.FontWeight.BOLD),
    ]
    enrichment_fields: list[ft.Control] = [
        ft.Text("Enrichment API Keys", size=16, color=CYAN, weight=ft.FontWeight.BOLD),
    ]
    misp_fields: list[ft.Control] = [
        ft.Text("MISP", size=16, color=CYAN, weight=ft.FontWeight.BOLD),
    ]

    llm_keys = {"llm_provider", "ollama_url", "openai_key", "anthropic_key", "openrouter_key"}
    misp_keys = {"misp_url", "misp_key", "censys_id", "censys_secret", "hybrid_analysis_key"}

    for key, label, is_password in FIELDS:
        # Determine signup provider
        base_name = (
            key.replace("_key", "").replace("_url", "").replace("_id", "").replace("_secret", "")
        )
        suffix_controls: list[ft.Control] = []
        if base_name in SIGNUP_URLS:
            suffix_controls.append(
                ft.IconButton(
                    icon=ft.Icons.OPEN_IN_NEW,
                    tooltip=f"Get a key: {SIGNUP_URLS[base_name]}",
                    icon_color=CYAN,
                    icon_size=18,
                    on_click=lambda e, p=base_name: on_signup_click(e, p),
                )
            )

        tf = ft.TextField(
            label=label,
            value=existing.get(key, ""),
            password=is_password,
            can_reveal_password=is_password,
            border_color=MATRIX_GREEN,
            focused_border_color=CYAN,
            text_style=ft.TextStyle(color=ft.Colors.WHITE),
            label_style=ft.TextStyle(color=ft.Colors.WHITE70),
            suffix=suffix_controls[0] if suffix_controls else None,
            expand=True,
        )
        inputs[key] = tf

        if key in llm_keys:
            llm_fields.append(tf)
        elif key in misp_keys:
            misp_fields.append(tf)
        else:
            enrichment_fields.append(tf)

    return ft.Column(
        controls=[
            ft.Text(
                "Settings",
                size=24,
                color=CYAN,
                weight=ft.FontWeight.BOLD,
            ),
            ft.Text(
                "Configure API keys and provider settings.",
                color=TEXT_SECONDARY,
                size=14,
            ),
            ft.Container(
                content=ft.Column(
                    controls=[
                        *llm_fields,
                        ft.Divider(color=ft.Colors.WHITE24),
                        *enrichment_fields,
                        ft.Divider(color=ft.Colors.WHITE24),
                        *misp_fields,
                        ft.Divider(color=ft.Colors.WHITE24),
                        ft.Row(
                            controls=[
                                ft.ElevatedButton(
                                    "Save",
                                    icon=ft.Icons.SAVE,
                                    bgcolor=MATRIX_GREEN,
                                    color=ft.Colors.BLACK,
                                    on_click=on_save_click,
                                ),
                                ft.ElevatedButton(
                                    "Test Keys",
                                    icon=ft.Icons.CHECK_CIRCLE,
                                    bgcolor=CYAN,
                                    color=ft.Colors.BLACK,
                                    on_click=on_test_click,
                                ),
                            ],
                            spacing=12,
                        ),
                        status_text,
                    ],
                    spacing=8,
                    scroll=ft.ScrollMode.AUTO,
                ),
                expand=True,
                padding=ft.Padding(top=8, bottom=8),
            ),
        ],
        spacing=8,
        expand=True,
    )


# Class alias for import compatibility
SettingsView = type("SettingsView", (), {"build": staticmethod(build_settings_view)})
