"""Settings screen — API key configuration with validation and persistence."""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path

import tomllib

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

from textual.app import ComposeResult
from textual.containers import VerticalScroll
from textual.screen import Screen
from textual.widgets import Button, Footer, Header, Input, Label, Static

logger = logging.getLogger(__name__)

# Provider signup URLs for help text
SIGNUP_URLS: dict[str, str] = {
    "openai": "https://platform.openai.com/signup",
    "anthropic": "https://console.anthropic.com/signup",
    "openrouter": "https://openrouter.ai/signup",
    "virustotal": "https://www.virustotal.com/gui/join-us",
    "abuseipdb": "https://www.abuseipdb.com/register",
    "shodan": "https://account.shodan.io/register",
    "otx": "https://otx.alienvault.com/signup",
    "urlscan": "https://urlscan.io/user/signup/",
    "hibp": "https://haveibeenpwned.com/API/Key",
    "greynoise": "https://www.greynoise.io/signup",
    "ipqs": "https://www.ipqualityscore.com/create-account",
    "numverify": "https://numverify.com/signup",
    "misp": "https://www.misp-project.org/",
    "censys": "https://censys.io/register",
    "hybrid_analysis": "https://www.hybrid-analysis.com/signup",
}


def _get_config_path() -> Path:
    """Return the path to the Lupe TOML config file."""
    from lupe.config import get_config_dir

    return get_config_dir() / "lupe.toml"


def validate_key_format(provider: str, value: str) -> bool:
    """Validate an API key format for the given provider.

    Returns True if the key appears valid, False otherwise.
    """
    if not value or not value.strip():
        return False

    value = value.strip()

    # URL validation for url fields
    if provider in ("ollama_url", "misp_url"):
        return value.startswith("http://") or value.startswith("https://")

    # Provider-specific prefix validation
    prefix_rules: dict[str, str] = {
        "openai": "sk-",
        "anthropic": "sk-ant-",
        "openrouter": "sk-or-",
    }

    if provider in prefix_rules:
        return value.startswith(prefix_rules[provider]) and len(value) > 10

    # Generic: non-empty is sufficient
    return len(value) > 0


def save_settings(settings: dict[str, str]) -> None:
    """Save settings dict to TOML config file with restrictive permissions.

    Creates parent directories if needed.
    On Unix, sets file permissions to 600 (owner read/write only).
    """
    config_path = _get_config_path()
    config_path.parent.mkdir(parents=True, exist_ok=True)

    # Filter out empty values
    clean = {k: v for k, v in settings.items() if v}

    # Write TOML
    lines = ["# Lupe CTI configuration", "# Generated by lupe-desktop TUI", ""]
    for key, value in sorted(clean.items()):
        # Escape quotes in values
        escaped = value.replace('"', '\\"')
        lines.append(f'{key} = "{escaped}"')

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Set restrictive permissions on Unix
    if sys.platform != "win32":
        try:
            os.chmod(config_path, 0o600)
        except OSError:
            logger.warning("Could not set permissions on %s", config_path)


def load_settings() -> dict[str, str]:
    """Load settings from the TOML config file.

    Returns an empty dict if the file doesn't exist.
    """
    config_path = _get_config_path()
    if not config_path.exists():
        return {}

    try:
        with open(config_path, "rb") as f:
            data = tomllib.load(f)
        # Flatten to str→str (TOML values may be various types)
        return {k: str(v) for k, v in data.items() if isinstance(v, str | int | float | bool)}
    except (tomllib.TOMLDecodeError, OSError):
        logger.warning("Failed to load config from %s", config_path, exc_info=True)
        return {}


# Field definitions: (id_suffix, placeholder, provider_key, is_password)
_FIELDS: list[tuple[str, str, str, bool]] = [
    ("llm-provider", "ollama / openai / anthropic / openrouter", "llm_provider", False),
    ("ollama-url", "Ollama URL (http://localhost:11434)", "ollama_url", False),
    ("openai-key", "OpenAI API key (sk-...)", "openai_key", True),
    ("anthropic-key", "Anthropic API key (sk-ant-...)", "anthropic_key", True),
    ("openrouter-key", "OpenRouter API key (sk-or-...)", "openrouter_key", True),
    ("virustotal-key", "VirusTotal key", "virustotal_key", True),
    ("abuseipdb-key", "AbuseIPDB key", "abuseipdb_key", True),
    ("shodan-key", "Shodan key", "shodan_key", True),
    ("otx-key", "OTX key", "otx_key", True),
    ("urlscan-key", "URLScan key", "urlscan_key", True),
    ("hibp-key", "HIBP key", "hibp_key", True),
    ("greynoise-key", "GreyNoise key", "greynoise_key", True),
    ("ipqs-key", "IPQS key", "ipqs_key", True),
    ("numverify-key", "NumVerify key", "numverify_key", True),
    ("misp-url", "MISP URL (https://misp.example.com)", "misp_url", False),
    ("misp-key", "MISP API key", "misp_key", True),
    ("censys-id", "Censys ID", "censys_id", False),
    ("censys-secret", "Censys Secret", "censys_secret", True),
    ("hybrid-analysis-key", "Hybrid Analysis key", "hybrid_analysis_key", True),
]


class SettingsScreen(Screen):
    """Screen for configuring API keys and provider settings.

    Features:
    - Live validation of key formats (sk-, sk-ant-, sk-or- prefixes)
    - Signup links shown for each provider
    - Save persists to ~/.config/lupe/lupe.toml with chmod 600
    - Load populates inputs from existing config
    """

    CSS = """
    .settings-group {
        margin: 0 2;
    }
    .key-input {
        margin: 0 0 1 0;
    }
    #signup-link {
        color: #00FFFF;
        margin: 1 2;
    }
    #save-status {
        margin: 1 2;
    }
    """

    BINDINGS = [
        ("escape", "app.pop_screen", "Back"),
        ("1", "app.push_screen('home')", "Home"),
        ("ctrl+s", "save", "Save"),
    ]

    def compose(self) -> ComposeResult:
        yield Header()
        with VerticalScroll():
            yield Static("[bold #00FFFF]Settings[/bold #00FFFF] — Configure API Keys and Provider")

            yield Label("[bold]LLM Provider[/bold]", classes="settings-group")
            yield Input(
                placeholder="ollama / openai / anthropic / openrouter",
                id="input-llm-provider",
                classes="key-input",
            )
            yield Input(
                placeholder="Ollama URL (http://localhost:11434)",
                id="input-ollama-url",
                classes="key-input",
            )

            yield Label("[bold]LLM API Keys[/bold]", classes="settings-group")
            yield Input(
                placeholder="OpenAI API key (sk-...)",
                id="input-openai-key",
                classes="key-input",
                password=True,
            )
            yield Input(
                placeholder="Anthropic API key (sk-ant-...)",
                id="input-anthropic-key",
                classes="key-input",
                password=True,
            )
            yield Input(
                placeholder="OpenRouter API key (sk-or-...)",
                id="input-openrouter-key",
                classes="key-input",
                password=True,
            )

            yield Label("[bold]Enrichment API Keys[/bold]", classes="settings-group")
            yield Input(
                placeholder="VirusTotal key",
                id="input-virustotal-key",
                classes="key-input",
                password=True,
            )
            yield Input(
                placeholder="AbuseIPDB key",
                id="input-abuseipdb-key",
                classes="key-input",
                password=True,
            )
            yield Input(
                placeholder="Shodan key", id="input-shodan-key", classes="key-input", password=True
            )
            yield Input(
                placeholder="OTX key", id="input-otx-key", classes="key-input", password=True
            )
            yield Input(
                placeholder="URLScan key",
                id="input-urlscan-key",
                classes="key-input",
                password=True,
            )
            yield Input(
                placeholder="HIBP key", id="input-hibp-key", classes="key-input", password=True
            )
            yield Input(
                placeholder="GreyNoise key",
                id="input-greynoise-key",
                classes="key-input",
                password=True,
            )
            yield Input(
                placeholder="IPQS key", id="input-ipqs-key", classes="key-input", password=True
            )
            yield Input(
                placeholder="NumVerify key",
                id="input-numverify-key",
                classes="key-input",
                password=True,
            )

            yield Label("[bold]MISP[/bold]", classes="settings-group")
            yield Input(
                placeholder="MISP URL (https://misp.example.com)",
                id="input-misp-url",
                classes="key-input",
            )
            yield Input(
                placeholder="MISP API key", id="input-misp-key", classes="key-input", password=True
            )

            yield Label("[bold]Censys[/bold]", classes="settings-group")
            yield Input(placeholder="Censys ID", id="input-censys-id", classes="key-input")
            yield Input(
                placeholder="Censys Secret",
                id="input-censys-secret",
                classes="key-input",
                password=True,
            )

            yield Label("[bold]Hybrid Analysis[/bold]", classes="settings-group")
            yield Input(
                placeholder="Hybrid Analysis key",
                id="input-hybrid-analysis-key",
                classes="key-input",
                password=True,
            )

            yield Static("", id="signup-link")
            yield Static("", id="save-status")
            yield Button("Save [Ctrl+S]", id="btn-save", variant="success")
            yield Button("Test Keys", id="btn-test", variant="primary")
        yield Footer()

    def on_mount(self) -> None:
        """Load existing settings on mount."""
        self._load_existing_settings()

    def _load_existing_settings(self) -> None:
        """Populate input fields from existing config file."""
        loaded = load_settings()
        for field_id, _, provider_key, _ in _FIELDS:
            input_widget = self.query_one(f"#input-{field_id}", Input)
            if provider_key in loaded:
                input_widget.value = loaded[provider_key]

    def on_input_changed(self, event: Input.Changed) -> None:
        """Validate input values on change and show signup links."""
        input_id = event.input.id or ""
        value = event.value

        # Find the provider key for this input
        provider_key = None
        for field_id, _, pkey, _ in _FIELDS:
            if f"input-{field_id}" == input_id:
                provider_key = pkey
                break

        if not provider_key:
            return

        # Live validation: color the border
        if value:
            is_valid = validate_key_format(provider_key, value)
            event.input.styles.border = ("solid", "green" if is_valid else "red")
        else:
            event.input.styles.border = ("solid", "#333333")

        # Show signup link for the focused provider
        signup_link = self.query_one("#signup-link", Static)
        base_name = (
            provider_key.replace("_key", "")
            .replace("_url", "")
            .replace("_id", "")
            .replace("_secret", "")
        )
        if base_name in SIGNUP_URLS:
            signup_link.update(f"Get a key: {SIGNUP_URLS[base_name]}")
        else:
            signup_link.update("")

    def action_save(self) -> None:
        """Save all settings to the config file."""
        settings: dict[str, str] = {}
        for field_id, _, provider_key, _ in _FIELDS:
            input_widget = self.query_one(f"#input-{field_id}", Input)
            value = input_widget.value.strip()
            if value:
                settings[provider_key] = value

        save_settings(settings)

        status = self.query_one("#save-status", Static)
        status.update("[green]Settings saved successfully![/green]")

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Handle button presses."""
        if event.button.id == "btn-save":
            self.action_save()
